import lucius from 'lucius'
import React from 'react'
import {render} from 'react-dom'
import muReact from 'mu-react'

var lu = lucius({get: true})
var fetch = muReact(lu, React)

fetch({
  components: ['service1', 'service2', 'activity'],
  styles: ['app', 'service', 'activity']
}, setup)

function patterns(app) {
  lu.add({role: 'activity', cmd: 'entry'}, function (args, cb) {
    var entries = app.state.entries.concat({
      service: args.info.service,
      action: args.info.action,
      result: args.result
    })
    app.setState({entries: entries})
    cb()
  })
}

function setup(deps) {
  var cmps = deps.components
  var theme = deps.styles
  var store = (state, root) => React.createClass({
    getInitialState: () => state,
    render: function () { return React.createElement(root, this.state) }
  })
  var App = store({entries: []}, function (props) {
    var styles = theme.app.styles
    return <div id={styles.content}>
      <style>
        {theme.app.css}
        {theme.service.css}
        {theme.activity.css}
      </style>
      <div>
        <div className={`${styles.header} ${styles.full}`}>
          <h1> foo </h1>
        </div>
        <div className={styles.half}>
          <cmps.Service1 styles={theme.service.styles}/>
        </div>
        <div className={styles.half}>
          <cmps.Service2 styles={theme.service.styles}/>
        </div>
        <div className={styles.full}>
          <cmps.Activity styles={theme.activity.styles} entries={props.entries}/>
        </div>
      </div>
      <footer id={styles.footer} className={styles.well}>
        <div id={styles.fuge}>
        <img id={styles.logo} src='img/fuge-logo.png'/>
        <p>Generated by <a href='http://github.com/apparatus/fuge'>fuge</a></p>
        </div>
      </footer>
    </div>
  })

  var app = render(<App/>, document.getElementById('app'))
  patterns(app) 
}